### ISSUE TITLE
cf local stage on Windows 10

### ISSUE THREAD

**Issue by sbromley07** [cloudfoundry-incubator/cflocal#15]
### Reproducable with the latest release?
Yes

### Versions:
Windows 10
Docker 17.09.1-ce-win42 (14687)
Go 1.9.2 windows/amd64

### What did you do?
`cf local stage {droplet-name} -p {path-to-jar} -s {app-name-in-pcf} `

### What did you expect to see?
A droplet building.

### What did you see instead?
```
Buildpack: will detect
runtime: nelems=170 nalloc=8 previous allocCount=7 nfreed=65535
fatal error: sweep increased allocation count

runtime stack:
runtime.throw(0x956dd8, 0x20)
        /usr/local/opt/go/libexec/src/runtime/panic.go:605 +0x9c
runtime.(*mspan).sweep(0x1340c58, 0xc042022600, 0xc042022600)
        /usr/local/opt/go/libexec/src/runtime/mgcsweep.go:298 +0x926
runtime.sweepone(0x43434d)
        /usr/local/opt/go/libexec/src/runtime/mgcsweep.go:113 +0x130
runtime.gosweepone.func1()
        /usr/local/opt/go/libexec/src/runtime/mgcsweep.go:137 +0x32
runtime.systemstack(0xc042018600)
        /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:344 +0x7e
runtime.mstart()
        /usr/local/opt/go/libexec/src/runtime/proc.go:1125

goroutine 3 [running]:
runtime.systemstack_switch()
        /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:298 fp=0xc04202bf70 sp=0xc04202bf68 pc=0x454f30
runtime.gosweepone(0x0)
        /usr/local/opt/go/libexec/src/runtime/mgcsweep.go:136 +0x51 fp=0xc04202bfa0 sp=0xc04202bf70 pc=0x41f921
runtime.bgsweep(0xc04203a000)
        /usr/local/opt/go/libexec/src/runtime/mgcsweep.go:55 +0xcb fp=0xc04202bfd8 sp=0xc04202bfa0 pc=0x41f42b
runtime.goexit()
        /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc04202bfe0 sp=0xc04202bfd8 pc=0x457bd1
created by runtime.gcenable
        /usr/local/opt/go/libexec/src/runtime/mgc.go:216 +0x5f

goroutine 1 [select, 2 minutes]:
github.com/sclevine/cflocal/vendor/golang.org/x/net/context/ctxhttp.Do(0x36e0f38, 0xc042052118, 0xc04222fb30, 0xc04207d4
00, 0xc0421e3368, 0x41113f, 0x10)
        /Users/stephen/go/src/github.com/sclevine/cflocal/vendor/golang.org/x/net/context/ctxhttp/ctxhttp.go:55 +0x1d2
github.com/sclevine/cflocal/vendor/github.com/docker/docker/client.(*Client).doRequest(0xc042336080, 0x36e0f38, 0xc04205
2118, 0xc04207d400, 0x80, 0xbc6980, 0xc042533400, 0x0, 0xc04207d400, 0x0)
        /Users/stephen/go/src/github.com/sclevine/cflocal/vendor/github.com/docker/docker/client/request.go:127 +0x75
github.com/sclevine/cflocal/vendor/github.com/docker/docker/client.(*Client).sendRequest(0xc042336080, 0x36e0f38, 0xc042
052118, 0x94463d, 0x3, 0xc04252a7e0, 0x54, 0xc0425583c0, 0xbc6980, 0xc042533400, ...)
        /Users/stephen/go/src/github.com/sclevine/cflocal/vendor/github.com/docker/docker/client/request.go:121 +0x145
github.com/sclevine/cflocal/vendor/github.com/docker/docker/client.(*Client).putRaw(0xc042336080, 0x36e0f38, 0xc04205211
8, 0xc04252a7e0, 0x54, 0xc0425583c0, 0xbc6980, 0xc042533400, 0x0, 0x3d, ...)
        /Users/stephen/go/src/github.com/sclevine/cflocal/vendor/github.com/docker/docker/client/request.go:63 +0xc4
github.com/sclevine/cflocal/vendor/github.com/docker/docker/client.(*Client).CopyToContainer(0xc042336080, 0x36e0f38, 0x
c042052118, 0xc04200ac80, 0x40, 0x947e7c, 0x8, 0xbc6980, 0xc042533400, 0xc0421e3700, ...)
        /Users/stephen/go/src/github.com/sclevine/cflocal/vendor/github.com/docker/docker/client/container_copy.go:43 +0
x285
github.com/sclevine/cflocal/vendor/github.com/sclevine/forge/engine.(*Container).ExtractTo(0xc042558390, 0x36e0eb0, 0xc0
420e7760, 0x947e7c, 0x8, 0xbccf60, 0xc042558390)
        /Users/stephen/go/src/github.com/sclevine/cflocal/vendor/github.com/sclevine/forge/engine/container.go:206 +0xfc
github.com/sclevine/cflocal/vendor/github.com/sclevine/forge.(*Stager).Stage(0xc042336280, 0xc0421fb8f0, 0xc042070990, 0
x36e0ed8, 0xc042070990, 0x0, 0x0)
        /Users/stephen/go/src/github.com/sclevine/cflocal/vendor/github.com/sclevine/forge/stager.go:115 +0x78b
github.com/sclevine/cflocal/cf/cmd.(*Stage).Run(0xc04232d1f0, 0xc04207c030, 0x6, 0xd, 0x0, 0x0)
        /Users/stephen/go/src/github.com/sclevine/cflocal/cf/cmd/stage.go:107 +0x9bb
github.com/sclevine/cflocal/cf.(*CF).Run(0xc0421ebd28, 0xc04207c030, 0x6, 0xd, 0xc0422039c0, 0xc91ea0)
        /Users/stephen/go/src/github.com/sclevine/cflocal/cf/cf.go:45 +0x258
github.com/sclevine/cflocal/plugin.(*Plugin).Run(0xc042203a00, 0xbce920, 0xc04232a210, 0xc04207c020, 0x7, 0xe)
        /Users/stephen/go/src/github.com/sclevine/cflocal/plugin/plugin.go:152 +0x124f
github.com/sclevine/cflocal/vendor/code.cloudfoundry.org/cli/plugin.Start(0xbc7ac0, 0xc042203a00)
        /Users/stephen/go/src/github.com/sclevine/cflocal/vendor/code.cloudfoundry.org/cli/plugin/plugin_shim.go:34 +0x2
a7
main.main()
        /Users/stephen/go/src/github.com/sclevine/cflocal/main.go:49 +0x412

goroutine 18 [syscall, 2 minutes]:
os/signal.signal_recv(0x0)
        /usr/local/opt/go/libexec/src/runtime/sigqueue.go:131 +0xad
os/signal.loop()
        /usr/local/opt/go/libexec/src/os/signal/signal_unix.go:22 +0x29
created by os/signal.init.0
        /usr/local/opt/go/libexec/src/os/signal/signal_unix.go:28 +0x48

goroutine 20 [chan receive, 2 minutes]:
main.main.func1(0xc0422968a0, 0xc0420443c0)
        /Users/stephen/go/src/github.com/sclevine/cflocal/main.go:26 +0x3b
created by main.main
        /Users/stephen/go/src/github.com/sclevine/cflocal/main.go:25 +0x1bd

goroutine 82 [chan send, 2 minutes]:
github.com/sclevine/cflocal/vendor/github.com/Microsoft/go-winio.ioCompletionProcessor(0x1d8)
        /Users/stephen/go/src/github.com/sclevine/cflocal/vendor/github.com/Microsoft/go-winio/file.go:133 +0x7e
created by github.com/sclevine/cflocal/vendor/github.com/Microsoft/go-winio.initIo
        /Users/stephen/go/src/github.com/sclevine/cflocal/vendor/github.com/Microsoft/go-winio/file.go:57 +0x87

goroutine 83 [chan receive, 2 minutes]:
github.com/sclevine/cflocal/vendor/github.com/Microsoft/go-winio.(*win32File).asyncIo(0xc04209aaa0, 0xc042558240, 0x0, 0
x0, 0x0, 0xc000000000, 0xbc69c0, 0xbc2368, 0xc04252a458, 0x0, ...)
        /Users/stephen/go/src/github.com/sclevine/cflocal/vendor/github.com/Microsoft/go-winio/file.go:167 +0x2af
github.com/sclevine/cflocal/vendor/github.com/Microsoft/go-winio.(*win32File).Read(0xc04209aaa0, 0xc0422ab000, 0x1000, 0
x1000, 0xc0424b3a40, 0x453e70, 0xc042022000)
        /Users/stephen/go/src/github.com/sclevine/cflocal/vendor/github.com/Microsoft/go-winio/file.go:190 +0xf3
github.com/sclevine/cflocal/vendor/github.com/Microsoft/go-winio.(*win32MessageBytePipe).Read(0xc0422a0680, 0xc0422ab000
, 0x1000, 0x1000, 0x403e86, 0xc042045f20, 0xc042296540)
        /Users/stephen/go/src/github.com/sclevine/cflocal/vendor/github.com/Microsoft/go-winio/pipe.go:116 +0x63
net/http.(*persistConn).Read(0xc0424ba000, 0xc0422ab000, 0x1000, 0x1000, 0xc0422e0da0, 0xc042045f78, 0x451ec0)
        /usr/local/opt/go/libexec/src/net/http/transport.go:1391 +0x147
bufio.(*Reader).fill(0xc042296780)
        /usr/local/opt/go/libexec/src/bufio/bufio.go:97 +0x121
bufio.(*Reader).Peek(0xc042296780, 0x1, 0x0, 0x0, 0x0, 0xc04252a480, 0x0)
        /usr/local/opt/go/libexec/src/bufio/bufio.go:129 +0x41
net/http.(*persistConn).readLoop(0xc0424ba000)
        /usr/local/opt/go/libexec/src/net/http/transport.go:1539 +0x18c
created by net/http.(*Transport).dialConn
        /usr/local/opt/go/libexec/src/net/http/transport.go:1186 +0xa35

goroutine 84 [select, 2 minutes]:
net/http.(*persistConn).writeLoop(0xc0424ba000)
        /usr/local/opt/go/libexec/src/net/http/transport.go:1759 +0x16c
created by net/http.(*Transport).dialConn
        /usr/local/opt/go/libexec/src/net/http/transport.go:1187 +0xa5a

goroutine 75 [select, 2 minutes]:
net/http.(*persistConn).roundTrip(0xc0424ba000, 0xc0425584b0, 0x0, 0x0, 0x0)
        /usr/local/opt/go/libexec/src/net/http/transport.go:1970 +0x60f
net/http.(*Transport).RoundTrip(0xc042342000, 0xc04207d400, 0xc042342000, 0x0, 0x0)
        /usr/local/opt/go/libexec/src/net/http/transport.go:413 +0x999
net/http.send(0xc04207d400, 0xbc4b40, 0xc042342000, 0x0, 0x0, 0x0, 0xc042071288, 0x0, 0xc042561d78, 0x1)
        /usr/local/opt/go/libexec/src/net/http/client.go:249 +0x1b0
net/http.(*Client).send(0xc04222fb30, 0xc04207d400, 0x0, 0x0, 0x0, 0xc042071288, 0x0, 0x1, 0x0)
        /usr/local/opt/go/libexec/src/net/http/client.go:173 +0x104
net/http.(*Client).Do(0xc04222fb30, 0xc04207d400, 0x0, 0x0, 0x0)
        /usr/local/opt/go/libexec/src/net/http/client.go:602 +0x294
github.com/sclevine/cflocal/vendor/golang.org/x/net/context/ctxhttp.Do.func1(0xc04222fb30, 0xc04207d400, 0x96aba0, 0xc04
20fac60)
        /Users/stephen/go/src/github.com/sclevine/cflocal/vendor/golang.org/x/net/context/ctxhttp/ctxhttp.go:48 +0x40
created by github.com/sclevine/cflocal/vendor/golang.org/x/net/context/ctxhttp.Do
        /Users/stephen/go/src/github.com/sclevine/cflocal/vendor/golang.org/x/net/context/ctxhttp/ctxhttp.go:47 +0xe4
```

**Comment by sclevine** [comment]
@sbromley07 Thanks for the report! Looking into this now.

**Comment by sclevine** [comment]
What version of CF Local do you have installed?

**Comment by sbromley07** [comment]
0.18.0

**Comment by sclevine** [comment]
Does the error reproduce every time you run `cf local stage ...`?

**Comment by sclevine** [comment]
Also, do you require an HTTP proxy to connect to the internet?
Can you provide a sample app that I can build to help reproduce the failure?

**Comment by sbromley07** [comment]
Its happening every time.

I don't have any HTTP proxies set up, but I am on a corporate network

**Comment by sclevine** [comment]
Do you have outbound access to the public internet?

**Comment by sclevine** [comment]
I suspect that this is actually a bug in Go 1.9.1: https://github.com/golang/go/issues/21717

You may have Go 1.9.2 installed locally, but Go isn't necessary to run CF Local. Version 0.18.0 was compiled with Go 1.9.1, which suffers from that bug. I'm building a beta with 1.9.2 right now, and I'll attach it here in a minute.

**Comment by sclevine** [comment]
This should be fixed on master. I'll cut 0.19.0 soon.

In the meantime, can you try out [this 0.19.0 RC](https://github.com/cloudfoundry-incubator/cflocal/files/1553570/cflocal-0.19.0-rc1-windows.zip)?

**Comment by sbromley07** [comment]
Getting a different exception now.   Although it seems to include similar function calls.

I am able to hit the public internet from the network I'm on.
```
Buildpack: will detect
runtime: nelems=170 nalloc=8 previous allocCount=7 nfreed=65535
fatal error: sweep increased allocation count

runtime stack:
runtime.throw(0x958fa8, 0x20)
        /usr/local/opt/go/libexec/src/runtime/panic.go:605 +0x9c
runtime.(*mspan).sweep(0x22a1810, 0xc042022600, 0xc042022600)
        /usr/local/opt/go/libexec/src/runtime/mgcsweep.go:298 +0x926
runtime.sweepone(0x43439d)
        /usr/local/opt/go/libexec/src/runtime/mgcsweep.go:113 +0x130
runtime.gosweepone.func1()
        /usr/local/opt/go/libexec/src/runtime/mgcsweep.go:137 +0x32
runtime.systemstack(0xc04201d300)
        /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:344 +0x7e
runtime.mstart()
        /usr/local/opt/go/libexec/src/runtime/proc.go:1135

goroutine 3 [running]:
runtime.systemstack_switch()
        /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:298 fp=0xc04202bf70 sp=0xc04202bf68 pc=0x454fb0
runtime.gosweepone(0x0)
        /usr/local/opt/go/libexec/src/runtime/mgcsweep.go:136 +0x51 fp=0xc04202bfa0 sp=0xc04202bf70 pc=0x41f931
runtime.bgsweep(0xc04203a000)
        /usr/local/opt/go/libexec/src/runtime/mgcsweep.go:55 +0xcb fp=0xc04202bfd8 sp=0xc04202bfa0 pc=0x41f43b
runtime.goexit()
        /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc04202bfe0 sp=0xc04202bfd8 pc=0x457c51
created by runtime.gcenable
        /usr/local/opt/go/libexec/src/runtime/mgc.go:216 +0x5f

goroutine 1 [select, 3 minutes]:
code.cloudfoundry.org/cflocal/vendor/golang.org/x/net/context/ctxhttp.Do(0x32923a8, 0xc042052120, 0xc04223d980, 0xc04207c200, 0xc0425fd368, 0x41113f, 0x10)
        /Users/stephen/go/src/code.cloudfoundry.org/cflocal/vendor/golang.org/x/net/context/ctxhttp/ctxhttp.go:55 +0x1d2
code.cloudfoundry.org/cflocal/vendor/github.com/docker/docker/client.(*Client).doRequest(0xc042344000, 0x32923a8, 0xc042052120, 0xc04207c200, 0x80, 0xbca980, 0xc0425240e0, 0x0, 0xc04207c200, 0x0)
        /Users/stephen/go/src/code.cloudfoundry.org/cflocal/vendor/github.com/docker/docker/client/request.go:127 +0x75
code.cloudfoundry.org/cflocal/vendor/github.com/docker/docker/client.(*Client).sendRequest(0xc042344000, 0x32923a8, 0xc042052120, 0x9467ff, 0x3, 0xc04255c120, 0x54, 0xc0425641e0, 0xbca980, 0xc0425240e0, ...)
        /Users/stephen/go/src/code.cloudfoundry.org/cflocal/vendor/github.com/docker/docker/client/request.go:121 +0x145
code.cloudfoundry.org/cflocal/vendor/github.com/docker/docker/client.(*Client).putRaw(0xc042344000, 0x32923a8, 0xc042052120, 0xc04255c120, 0x54, 0xc0425641e0, 0xbca980, 0xc0425240e0, 0x0, 0x1, ...)
        /Users/stephen/go/src/code.cloudfoundry.org/cflocal/vendor/github.com/docker/docker/client/request.go:63 +0xc4
code.cloudfoundry.org/cflocal/vendor/github.com/docker/docker/client.(*Client).CopyToContainer(0xc042344000, 0x32923a8, 0xc042052120, 0xc042372000, 0x40, 0x94a03e, 0x8, 0xbca980, 0xc0425240e0, 0xc0425fd700, ...)
        /Users/stephen/go/src/code.cloudfoundry.org/cflocal/vendor/github.com/docker/docker/client/container_copy.go:43 +0x285
code.cloudfoundry.org/cflocal/vendor/github.com/sclevine/forge/engine.(*Container).ExtractTo(0xc0425641b0, 0x32920e8, 0xc04213c720, 0x94a03e, 0x8, 0xbd1760, 0xc0425641b0)
        /Users/stephen/go/src/code.cloudfoundry.org/cflocal/vendor/github.com/sclevine/forge/engine/container.go:208 +0xfc
code.cloudfoundry.org/cflocal/vendor/github.com/sclevine/forge.(*Stager).Stage(0xc042344200, 0xc042214620, 0xc04213e058, 0x3292110, 0xc04213e058, 0x0, 0x0)
        /Users/stephen/go/src/code.cloudfoundry.org/cflocal/vendor/github.com/sclevine/forge/stager.go:115 +0x78b
code.cloudfoundry.org/cflocal/cf/cmd.(*Stage).Run(0xc04232f0a0, 0xc04207c030, 0x6, 0xd, 0x0, 0x0)
        /Users/stephen/go/src/code.cloudfoundry.org/cflocal/cf/cmd/stage.go:107 +0x9bb
code.cloudfoundry.org/cflocal/cf.(*CF).Run(0xc0421edd28, 0xc04207c030, 0x6, 0xd, 0xc0421ad9c0, 0xc95ec0)
        /Users/stephen/go/src/code.cloudfoundry.org/cflocal/cf/cf.go:45 +0x258
code.cloudfoundry.org/cflocal/plugin.(*Plugin).Run(0xc0421ada00, 0xbd2940, 0xc04232c1a0, 0xc04207c020, 0x7, 0xe)
        /Users/stephen/go/src/code.cloudfoundry.org/cflocal/plugin/plugin.go:152 +0x124f
code.cloudfoundry.org/cflocal/vendor/code.cloudfoundry.org/cli/plugin.Start(0xbcb3c0, 0xc0421ada00)
        /Users/stephen/go/src/code.cloudfoundry.org/cflocal/vendor/code.cloudfoundry.org/cli/plugin/plugin_shim.go:34 +0x2a7
main.main()
        /Users/stephen/go/src/code.cloudfoundry.org/cflocal/main.go:49 +0x412

goroutine 18 [syscall, 3 minutes]:
os/signal.signal_recv(0x0)
        /usr/local/opt/go/libexec/src/runtime/sigqueue.go:131 +0xad
os/signal.loop()
        /usr/local/opt/go/libexec/src/os/signal/signal_unix.go:22 +0x29
created by os/signal.init.0
        /usr/local/opt/go/libexec/src/os/signal/signal_unix.go:28 +0x48

goroutine 20 [chan receive, 3 minutes]:
main.main.func1(0xc0422988a0, 0xc0420443c0)
        /Users/stephen/go/src/code.cloudfoundry.org/cflocal/main.go:26 +0x3b
created by main.main
        /Users/stephen/go/src/code.cloudfoundry.org/cflocal/main.go:25 +0x1bd

goroutine 53 [select, 3 minutes]:
net/http.(*persistConn).writeLoop(0xc0424fa000)
        /usr/local/opt/go/libexec/src/net/http/transport.go:1759 +0x16c
created by net/http.(*Transport).dialConn
        /usr/local/opt/go/libexec/src/net/http/transport.go:1187 +0xa5a

goroutine 107 [select, 3 minutes]:
net/http.(*persistConn).roundTrip(0xc0424fa000, 0xc0425642d0, 0x0, 0x0, 0x0)
        /usr/local/opt/go/libexec/src/net/http/transport.go:1970 +0x60f
net/http.(*Transport).RoundTrip(0xc042342000, 0xc04207c200, 0xc042342000, 0x0, 0x0)
        /usr/local/opt/go/libexec/src/net/http/transport.go:413 +0x999
net/http.send(0xc04207c200, 0xbc8b40, 0xc042342000, 0x0, 0x0, 0x0, 0xc042568028, 0x0, 0xc0423d1d78, 0x1)
        /usr/local/opt/go/libexec/src/net/http/client.go:249 +0x1b0
net/http.(*Client).send(0xc04223d980, 0xc04207c200, 0x0, 0x0, 0x0, 0xc042568028, 0x0, 0x1, 0x0)
        /usr/local/opt/go/libexec/src/net/http/client.go:173 +0x104
net/http.(*Client).Do(0xc04223d980, 0xc04207c200, 0x0, 0x0, 0x0)
        /usr/local/opt/go/libexec/src/net/http/client.go:602 +0x294
code.cloudfoundry.org/cflocal/vendor/golang.org/x/net/context/ctxhttp.Do.func1(0xc04223d980, 0xc04207c200, 0x96c6c0, 0xc0420fa480)
        /Users/stephen/go/src/code.cloudfoundry.org/cflocal/vendor/golang.org/x/net/context/ctxhttp/ctxhttp.go:48 +0x40
created by code.cloudfoundry.org/cflocal/vendor/golang.org/x/net/context/ctxhttp.Do
        /Users/stephen/go/src/code.cloudfoundry.org/cflocal/vendor/golang.org/x/net/context/ctxhttp/ctxhttp.go:47 +0xe4

goroutine 51 [chan send, 3 minutes]:
code.cloudfoundry.org/cflocal/vendor/github.com/Microsoft/go-winio.ioCompletionProcessor(0x428)
        /Users/stephen/go/src/code.cloudfoundry.org/cflocal/vendor/github.com/Microsoft/go-winio/file.go:133 +0x7e
created by code.cloudfoundry.org/cflocal/vendor/github.com/Microsoft/go-winio.initIo
        /Users/stephen/go/src/code.cloudfoundry.org/cflocal/vendor/github.com/Microsoft/go-winio/file.go:57 +0x87

goroutine 52 [chan receive, 3 minutes]:
code.cloudfoundry.org/cflocal/vendor/github.com/Microsoft/go-winio.(*win32File).asyncIo(0xc042244000, 0xc042564060, 0x0, 0x0, 0x0, 0xc000000000, 0xbca9c0, 0xbc6368, 0xc042474380, 0x411a74, ...)
        /Users/stephen/go/src/code.cloudfoundry.org/cflocal/vendor/github.com/Microsoft/go-winio/file.go:167 +0x2af
code.cloudfoundry.org/cflocal/vendor/github.com/Microsoft/go-winio.(*win32File).Read(0xc042244000, 0xc042489000, 0x1000, 0x1000, 0xc042485a40, 0x453ef0, 0xc042022000)
        /Users/stephen/go/src/code.cloudfoundry.org/cflocal/vendor/github.com/Microsoft/go-winio/file.go:190 +0xf3
code.cloudfoundry.org/cflocal/vendor/github.com/Microsoft/go-winio.(*win32MessageBytePipe).Read(0xc0420344a0, 0xc042489000, 0x1000, 0x1000, 0x403e86, 0xc0423b6900, 0xc0420fa1e0)
        /Users/stephen/go/src/code.cloudfoundry.org/cflocal/vendor/github.com/Microsoft/go-winio/pipe.go:116 +0x63
net/http.(*persistConn).Read(0xc0424fa000, 0xc042489000, 0x1000, 0x1000, 0xc042149dc0, 0xc0423b6958, 0x451f40)
        /usr/local/opt/go/libexec/src/net/http/transport.go:1391 +0x147
bufio.(*Reader).fill(0xc0421304e0)
        /usr/local/opt/go/libexec/src/bufio/bufio.go:97 +0x121
bufio.(*Reader).Peek(0xc0421304e0, 0x1, 0x0, 0x0, 0x0, 0xc0423b7020, 0x0)
        /usr/local/opt/go/libexec/src/bufio/bufio.go:129 +0x41
net/http.(*persistConn).readLoop(0xc0424fa000)
        /usr/local/opt/go/libexec/src/net/http/transport.go:1539 +0x18c
created by net/http.(*Transport).dialConn
        /usr/local/opt/go/libexec/src/net/http/transport.go:1186 +0xa35
```

**Comment by sclevine** [comment]
The fatal exception `fatal error: sweep increased allocation count` happens when the Go GC runs and ends up with more allocated memory instead of less allocated memory. It can be caused by a bug in the program, but usually only when there are data races.

I'm looking at https://github.com/golang/go/issues/22781 as a possible cause, and still trying to replicate the failure.

**Comment by sclevine** [comment]
Let me know if this is working for you in [v0.19.0](https://github.com/cloudfoundry-incubator/cflocal/releases/tag/v0.19.0). I am not able to reproduce this on Windows 10 Enterprise running in VMware Fusion.
